<?php

namespace Daalder\BusinessCentral\Tests\Repositories;

use Daalder\BusinessCentral\API\HttpClient;
use Daalder\BusinessCentral\Repositories\CustomerRepository;
use Daalder\BusinessCentral\Models\CustomerBusinessCentral;
use Daalder\BusinessCentral\Tests\TestCase as DaalderTestCase;
use Mockery;
use Pionect\Daalder\Models\Customer\Customer;

/**
 * Class CustomerRepositoryTest
 * @package Daalder\BusinessCentral\Tests\Repositories
 * @covers DimensionValueRepository
 */
class DimensionValueRepositoryTest extends DaalderTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @covers DimensionValueRepository::pullReferences()
     */
    public function testPullReferences()
    {
        $this->markTestIncomplete();
    }

}
