name: run-tests

on: [push, pull_request]
env:
    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DB_DATABASE: unit_tests
jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.0]
                laravel: [9.*]
                dependency-version: [prefer-stable]

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            - id: foo
              uses: Daalder/run-tests-action@1.3.5
              env:
                  PACKAGIST_TOKEN: ${{ secrets.DAALDER }}
    slack_notification:
        needs: [tests]
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Run Slack Notification
              uses: rohammosalli/slack-action@master
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BEARER_TOKEN }}
                  SLACK_CHANNEL: "pipelines-notifications"
                  GITHUB_TOKEN: ${{ github.token }}
                  GITHUB_RUN_ID: ${{ github.run_id }}
                  REPO_OWNER: ${{ github.repository_owner }}
                  REPO_NAME: ${{ github.event.repository.name }}
                  RUN_ID: ${{ github.run_id }}
                  SEND_SUCCESS_MESSAGE: "true"